spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dealkaro_local
    username: postgres
    password: admin

  flyway:
    locations: classpath:db/seed/local,classpath:db/migration

cors:
  allowed-origins: http://localhost:3000,http://localhost:8081
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
